### ISSUE TITLE
unwanted switching toggle entities while scrolling on phone etc

### ISSUE THREAD

**Issue by Murcin86** [marcokreeft87/room-card#106]
Version: 1.07.00 but I guest for all of them

**Describe the bug**
On and off (toggle) entities on phone where we`re using finger and scrolling entities turn on... but should on when I press on that button, please have a look on video, this is not happened on other entities or some other functions on HA :)

**To Reproduce**
use phone or watch a movie..

**Screenshots**
https://youtu.be/uit821515mQ

**Desktop (please complete the following information):**
On laptop we don`t use touch screen but will be the same.

 - Device:iphone and adroid

**Comment by marcokreeft87** [comment]
I have been searching for a solution for this for a while now. The problem is, how would you detect you are scrolling on mobile? Because you want to toggle when you tap the icon and down want to lose the hold and double tap functionality. Imo this is a shortcoming on every phone. I am using the example from Home Assistant to put the actions on the icons so this is how it should be handled according to HA. For now I advice to either don't put too many entities in the room card ( I know, this is not really an option ) or leave an empty space for scrolling. I will try to fix this but I cant think of a solution for now

**Comment by hugalafutro** [comment]
I already asked about this on ha forum and was thinking about this more. There has to be a way though as the "normal" ha cards work properly. Obviously I am not a dev so I'm just pulling ideas from you know where, but maybe there is a way to give bigger priority to the "drag" action over "tap" or something.

There are even places where it works normally inside room-card.

In following screenshot, the 2 graphs at top are "normal" cards, The **Media** card is room card, including the mini-media-player, under it is another room card **Gaming**, under which is again "normal" card with graph:
![image](https://user-images.githubusercontent.com/30209689/197384918-19ef7e6d-36aa-49c0-a350-1920440eb735.png)

Following places work normally even inside room-card as in they scroll the ui and don't pop the more-info dialog when I touch and drag on them
- anything in the top row of room-card (the zzz, name and info_entities: )
- any part of the mini-media-player card embedded in the room card - even if I touch the on/off button (or any other) of mini-media-card it lights up as if triggered, but immediately goes off when I start dragging
- any empty part of room-card

I tried embedding room-card as cards: into another room-card and that sort of works: it still triggers the entity, but it scrolls the ui without popping up the more-info dialog, but it wasn't 100%. (room-cardception)

No idea if anything of the above is useful I'm just a bit high and thinking aloud sorry.

**Comment by marcokreeft87** [comment]
Yes ofcourse  the empty part, the media-card and others cards without switches in it are working. But the problem here is there is no way to detect a double tap or hold action on mobile without checking the time between clicks. The reason the top part of the room card is working is because you cant double tap or hold info_entities. Other cards like graph and media card are working when you scroll is because they wont toggle and certainly dont have a hold action on the whole card. Like this topic says: https://stackoverflow.com/questions/25777826/onclick-works-but-ondoubleclick-is-ignored-on-react-component there is no real working way you can register both click, double click and hold without losing something.

**Comment by hugalafutro** [comment]
I see. Speaking for myself I only use the double_tap in 2 or 3 entities which I could work around easily if it meant "proper" scrolling, but of course other might use it differently. Not sure how easy/feasible would it be to implement it as an option, i.e. you could either use double_tap OR have the scrolling work right.

In any case I'm pretty happy with the compact look I can achieve with room-card already, this is just nitpicking really. Keep up the great work!

**Comment by marcokreeft87** [comment]
Yeah no worries. I have this issue too but I don't use the UI that much. Most is automated in my house

**Comment by marcokreeft87** [comment]
@hugalafutro Nice use of the card btw

**Comment by Murcin86** [comment]
I agree that is not easy to detect scrolling and tap to know what is needed but... for all other functions that works :)
I`ve use a lot custom:button-card - and there is working :) also on typical entities view... works :)
this is no problem for working on laptop... but I guest we all using phone for working with that and custom:room-card is brilliant because makes everything more clear and more organized... so would be very good that will be working like all the others functionality of HA... I`m just plc programmer and I would solve it with falling slope (F_TRIG functions) - now looks like button detect rising slope and that why happened like this :)

**Comment by smenzer** [comment]
I have the same concern with the room card... i toggle lights all the time when i'm scrolling. There's definitely a difference between this card and standard entities in home assistant (and in general, any other "clickable" places on the phone). there's something different about how taps are handled here. I haven't dug into the code here yet to see what's going on, but I wonder if there's some event handler that can be picked up that the phone detects as a tap vs a swipe/scroll that can be leveraged?

**Comment by TTLucian** [comment]
I've also ran into this issue. Same 4 me, scrolling works ok with custom:button-card but with room card everything touched gets toggled.

**Comment by Necroneco** [comment]
Same problem, hope it can be resolved

**Comment by marcokreeft87** [comment]
I think I've got the solution! New release incoming

**Comment by marcokreeft87** [comment]
@Necroneco @TTLucian @smenzer @Murcin86 @hugalafutro  Can you guys check if this update fixes the problem for you?

**Comment by Necroneco** [comment]
Nice! Good job!

**Comment by Murcin86** [comment]
> @Necroneco @TTLucian @smenzer @Murcin86 @hugalafutro  Can you guys check if this update fixes the problem for you?

Works !! Great work!! Thanks !!
