### ISSUE TITLE
Handle breaking change for ha-icon

### ISSUE THREAD

**Issue by elupus** [marcokreeft87/room-card#313]
**Which version of Room Card?**
1.08.02

**Describe the bug**

Some state icon's are no longer displayed correct.

**To Reproduce**

**Expected behavior**
Correct state icon

**Screenshots**
<img width="761" alt="image" src="https://github.com/marcokreeft87/room-card/assets/482976/d75651b5-0128-4b25-8192-9012238b8bc2">

See bottom left, and bottom right. There should be a outlet icon on the right.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 

**Additional context**

https://developers.home-assistant.io/blog/2024/01/30/ha-state-icon-properties-changes/

**YAML**

**Comment by jamesgid-gc** [comment]
I am seeing the same behaviour since updating HA to the latest version. Although the icons are only displaying incorrectly through my web-browser on my desktop computer. On my android phone (Google Pixel 7) the icons are still correct.

room-card version: v1.08.02

Desktop (please complete the following information):
OS: Windows 11
Browser Chrome
Version 121.0.6167.14

Desktop:
![image](https://github.com/marcokreeft87/room-card/assets/154476168/365457d0-d70a-4a1e-8d2a-7a26f0085ec2)
![image](https://github.com/marcokreeft87/room-card/assets/154476168/f1590095-d504-4f92-8b18-c35ba1652a39)

Android Phone (and what they looked liked before on the desktop):
![image](https://github.com/marcokreeft87/room-card/assets/154476168/cf9d47f1-e0bb-4ecf-9ae6-5084eb73f995)
![image](https://github.com/marcokreeft87/room-card/assets/154476168/0f3dce21-95fa-408a-bc34-15564002e53c)

**Comment by DeWaHa** [comment]
I have the same problemen on my Android Phone and tablet.
The mediaplayer, presence, motion, smoke, co and heat icons are missing.

**Comment by elupus** [comment]
Did an initial fix attempt here: https://github.com/marcokreeft87/room-card/pull/314 but tests needs to be fixed and the fix needs to be actually tested :)

**Comment by TTLucian** [comment]
Same problem here. Icons are all messed uo!

**Comment by Belrix** [comment]
Ditto.

**Comment by boredomwontgetus** [comment]
+1

**Comment by marcokreeft87** [comment]
Seems to be fixed by the change of @elupus Please download the latest version everyone!

**Comment by calielc** [comment]
It is a beta version `1.08.03` (https://github.com/marcokreeft87/room-card/releases/tag/1.08.03)

**Comment by DeWaHa** [comment]
How do we install this bèta not using Hacs?
Can someone explain please?

**Comment by TTLucian** [comment]
Got it. Go to room card in HACS, hit the 3 dots upper right, click update information then click redownload.

**Comment by marcokreeft87** [comment]
> It is a beta version `1.08.03` (https://github.com/marcokreeft87/room-card/releases/tag/1.08.03)

No its not? 

![image](https://github.com/marcokreeft87/room-card/assets/10223677/69426e7f-70a4-4873-9878-bd8a2eab0ba1)

**Comment by marcokreeft87** [comment]
HACS is just bugging again as always

**Comment by DeWaHa** [comment]
Thanks TTLucian and macrokreeft87. Problem solved.

**Comment by marcokreeft87** [comment]
> Did an initial fix attempt here: https://github.com/marcokreeft87/room-card/pull/314 but tests needs to be fixed and the fix needs to be actually tested :)

Can you confirm it's fixed with the new version?
